services:
  db:
    image: postgres:16-alpine
    container_name: mypills-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/internal/infra/postgres/init:/docker-entrypoint-initdb.d

volumes:
  pgdata: